# CD pipeline for NutriFinder
# This pipeline builds and pushes the NutriFinderServer Docker image to Docker Hub
# Triggered automatically when the CI pipeline (BuildAndTest) completes successfully on 'main'

trigger: none
pr: none

# Reference the CI pipeline that must complete before this CD pipeline runs
resources:
  pipelines:
    - pipeline: BuildAndTest  
      source: BuildAndTest     
      trigger:
        branches:
          include:
            - main

# Use self hosted default agent pool 
pool:
  name: Default

steps:
  # Step 1: Build Docker image with two tags: latest and unique build ID
  - task: CmdLine@2
    displayName: 'Build Docker image'
    inputs:
      script: docker build -t mtbonde/nutrifinder:$(Build.SourceBranchName) -t mtbonde/nutrifinder:latest ./NutriFinderClient

  # Step 2: Authenticate and push both tags to Docker Hub
  - task: CmdLine@2
    displayName: 'Push image to Docker Hub'
    inputs:
      script: docker push --all-tags mtbonde/nutrifinder

  # Step 3: Optional cleanup to remove unused images from the agent
  - task: CmdLine@2
    displayName: 'Cleanup old Docker images'
    inputs:
      script: |
        echo y | docker image prune -a --force
