# Development Docker compose for running server and mongo db 
# to use: "docker-compose up -d"

# Name a shared network for all services
networks:
  default:
    name: nutrifinder-net

# Define our application services
services:
  mongo:
    image: mongo:7.0.21
    ports:
      - "27017:27017"
    container_name: nutrifinder-mongo

  nutrifinderserver:
    build:
      context: .
      dockerfile: NutriFinder.Server/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Mongo__ConnectionString=mongodb://mongo:27017