# CD pipeline for NutriFinder server
# This pipeline builds and pushes the NutriFinder Docker image to Docker Hub
# Triggered automatically when the CI pipeline (BuildAndTest) completes successfully on 'main'

trigger: none
pr: none

# Reference the CI pipeline that must complete before this CD pipeline runs
resources:
  pipelines:
    - pipeline: BuildAndTest
      source: BuildAndTest
      trigger:
        branches:
          include:
            - main
        paths:
          include:
            - NutriFinder.Server/**

# Use self hosted default agent pool 
pool:
  name: Default

steps:
  # Step 1: Build Docker image with two tags: latest and unique build ID
  - task: CmdLine@2
    displayName: 'Build Docker image'
    inputs:
      script: docker build -t mtbonde/nutrifinder-server:$(Build.BuildNumber) -t mtbonde/nutrifinder-server:latest -f NutriFinder.Server/Dockerfile .
         # . means build from solution root, so path in dockerfile are valid

  # Step 2: Login agent and push both tags to Docker Hub
  - task: CmdLine@2
    displayName: 'Docker login'
    inputs:
      script: docker login -u %DOCKER_USERNAME% -p %DOCKER_PASSWORD%
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  - task: CmdLine@2
    displayName: 'Push image to Docker Hub'
    inputs:
      script: docker push --all-tags mtbonde/nutrifinder-server

  # Step 3: Cleanup to remove unused images from the agent
  - task: CmdLine@2
    displayName: 'Cleanup old Docker images'
    inputs:
      script: |
        echo y | docker image prune -a --force
