name: CD – Client

on:
  workflow_run:
    workflows: [ Build and Test ]
    types:
      - completed

jobs:
  build-and-push-client:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push NutriFinderClient
        uses: docker/build-push-action@v5
        with:
          context: .
          file: NutriFinderClient/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nutrifinder-client:latest
            ${{ secrets.DOCKER_USERNAME }}/nutrifinder-client:${{ github.run_number }}

      - name: Cleanup
        run: docker image prune -a -f
