name: CD – Server

on:
  push:
    branches:
      - main

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push NutriFinder Server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: NutriFinder.Server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nutrifinder-server:latest
            ${{ secrets.DOCKER_USERNAME }}/nutrifinder-server:${{ github.run_number }}
            ${{ secrets.DOCKER_USERNAME }}/nutrifinder-server:${{ github.sha }}

      - name: Cleanup
        run: docker image prune -f